##
# This function will generate a settings file for the Xilinx Vitis compiler with the desired memory mapping
#
##
function(generate_compiler_settings_xilinx)
    file(READ "${base_file}" file_content)
    file(WRITE "${settings_f}" "[connectivity]\n")
    string(REGEX MATCHALL "nk=[^\n]+\n" number_kernels_string "${file_content}")
    string(REGEX REPLACE ";" "" number_kernels_string  "${number_kernels_string}")
    string(REGEX REPLACE "{TOTAL_KERNEL_NUMBER}" ${NUM_REPLICATIONS} mod_file_content "${number_kernels_string}")
    file(APPEND "${settings_f}" "${mod_file_content}")
    math(EXPR iterator "${NUM_REPLICATIONS} - 1")
    message(STATUS ${iterator})
    string(REGEX MATCHALL "slr=[^\n]+\n" slr_placement_string "${file_content}")
    string(REGEX REPLACE ";" "" slr_placement_string  "${slr_placement_string}")
    foreach(number RANGE ${iterator})
        math(EXPR inc_number "${number} + 1")
        math(EXPR number "${number} % 3")
        string(REGEX REPLACE "{KERNEL_NUMBER}" ${inc_number} mod_file_content "${slr_placement_string}")
        string(REGEX REPLACE "{KERNEL_NUMBER_DEC}" ${number} mod_file_content "${mod_file_content}")
        file(APPEND "${settings_f}" "${mod_file_content}")
    endforeach()
    file(APPEND "${settings_f}" "\n")
    string(REGEX MATCHALL "sp=[^\n]+\n" hbm_placement_string "${file_content}")
    string(REGEX REPLACE ";" "" hbm_placement_string  "${hbm_placement_string}")
    foreach(number RANGE ${iterator})
        math(EXPR inc_number "${number} + 1")
        string(REGEX REPLACE "{KERNEL_NUMBER}" ${inc_number} mod_file_content "${hbm_placement_string}")
        string(REGEX REPLACE "{KERNEL_NUMBER_DEC}" ${number} mod_file_content "${mod_file_content}")
        file(APPEND "${settings_f}" "${mod_file_content}")
    endforeach()
    file(APPEND "${settings_f}" "\n")

endfunction()

generate_compiler_settings_xilinx()
